services:
  etl:
    container_name: etl_aviationstack
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python src/main.py
    volumes:
      - .:/app/
    env_file:
      - ./.env.dev
    networks:
      - local_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: etl_aviationstack_postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - local_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  local_network:
    driver: bridge

volumes:
    postgres_data: